### ISSUE TITLE
タグの表記ゆれ

### ISSUE THREAD

**Issue by shgtkshruch** [codeforjapan/vs-covid19#3]
「教育、学習支援」と「教育・学習支援」というタグが 2つあります。
意味的には同じだと思うので、1つにまとまっている方がわかりやすいかなと思いました。

![スクリーンショット 2020-03-11 0 30 14](https://user-images.githubusercontent.com/5207601/76329236-a6b95d00-632f-11ea-9da0-3d4a1fef4cc8.png)

**Comment by taisukef** [comment]
ありがとうございます！
データ作成している人に本件、共有しました

**Comment by taisukef** [comment]
ひとまずプログラムで表記ゆれ解消しました

**Comment by shgtkshruch** [comment]
早速ありがとうございます！
